spring:
  datasource:
    url: "jdbc:mysql://192.168.100.34:3306/mini-SN"
    username: usr1
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: validation
server:
  port: 80